[[feature]]
name = "plan_project"
requirements = [
    "goal of this project is to learn arcade",
    "each task should learn new skill",
    "create objects for next task"
]

[[feature]]
name = "learn_by_ai"
requirements = [
    "learn new usefull arcade skill using ai chats"
]

[[feature]]
name = "learn_by_arcade_page"
requirements = [
    "learn new usefull arcade skill using arcade page"
]