[[feature]]
name = "plan_project"
requirements = [
    "goal of this project is to learn arcade",
    "each task should learn new skill",
    "create objects for next task"
]

[[feature]]
name = "learn_skill"
requirements = [
    "learn new usefull arcade skill"
]
