[[file]]
id = 1
feature = "plan_project"
task = "plan_task"
file_name = "merged.toml"
path = "src/learn_by_ai"

[[file]]
id = 2
feature = "learn_skill"
task = "window_setup"
file_name = "window_setup.py"
path = "src/learn_by_ai"

[[file]]
id = 3
feature = "learn_skill"
task = "draw_shapes"
file_name = "draw_shapes.py"
path = "src/learn_by_ai"

[[file]]
id = 4
feature = "learn_skill"
task = "sprite_basics"
file_name = "sprite_basics.py"
path = "src/learn_by_ai"

[[file]]
id = 5
feature = "learn_skill"
task = "keyboard_input"
file_name = "keyboard_input.py"
path = "src/learn_by_ai"

[[file]]
id = 6
feature = "learn_skill"
task = "mouse_interaction"
file_name = "mouse_interaction.py"
path = "src/learn_by_ai"

[[file]]
id = 7
feature = "learn_skill"
task = "animation_basics"
file_name = "animation_basics.py"
path = "src/learn_by_ai"

[[file]]
id = 8
feature = "learn_skill"
task = "collision_detection"
file_name = "collision_detection.py"
path = "src/learn_by_ai"

[[file]]
id = 9
feature = "learn_skill"
task = "scene_management"
file_name = "scene_management.py"
path = "src/learn_by_ai"

[[file]]
id = 10
feature = "learn_by_arcade_page"
task = "starting_template"
file_name = "starting_template_comments.py"
path = "src/learn_by_arcade_page"

[[file]]
id = 11
feature = "learn_by_arcade_page"
task = "starting_template"
file_name = "starting_template.py"
path = "src/learn_by_arcade_page"

