[[file]]
id = 1
feature = "plan_project"
task = "plan_task"
file_name = "merged.toml"
path = "src"

[[file]]
id = 2
feature = "learn_skill"
task = "window_setup"
file_name = "window_setup.py"
path = "src"

[[file]]
id = 3
feature = "learn_skill"
task = "draw_shapes"
file_name = "draw_shapes.py"
path = "src"