[[task]]
feature = "plan_project"
name = "plan_task"
requirements = [ "plan task to teach me new arcade skill", "use toml objects to define it",]
context_files = [ 1,]
save_file = 1
assigned_to = "planner"
status = "tested"

[[task]]
feature = "learn_skill"
name = "window_setup"
requirements = [ "create basic arcade window", "set window dimensions", "set window title", "set background color",]
context_files = [ 2,]
save_file = 2
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "draw_shapes"
requirements = [ "draw basic shapes", "learn arcade shape primitives", "draw circles, rectangles, lines", "set colors and positions",]
context_files = [ 3,]
save_file = 3
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "sprite_basics"
requirements = [ "create and display sprites", "load sprite from image", "position and scale sprites", "basic sprite properties",]
context_files = [ 4,]
save_file = 4
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "keyboard_input"
requirements = [ "handle keyboard events", "move object with keyboard", "detect key presses and releases", "simple keyboard controls",]
context_files = [ 5,]
save_file = 5
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "mouse_interaction"
requirements = [ "handle mouse events", "detect mouse clicks", "get mouse position", "interact with objects using mouse",]
context_files = [ 6,]
save_file = 6
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "animation_basics"
requirements = [ "create simple animations", "use sprite lists", "animate sprite properties", "basic frame-based animation",]
context_files = [ 7,]
save_file = 7
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "collision_detection"
requirements = [ "detect collisions between objects", "use hitboxes", "simple collision responses", "sprite collision methods",]
context_files = [ 8,]
save_file = 8
assigned_to = "implementer"
status = "tested"

[[task]]
feature = "learn_skill"
name = "scene_management"
requirements = [ "create multiple scenes", "switch between scenes", "scene lifecycle methods", "basic game flow",]
context_files = [ 9,]
save_file = 9
assigned_to = "implementer"
status = "tested"

